name: Build ESP Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build ESP Arduino project
        uses: arduino/compile-sketches@v1
        with: 
          fqbn: esp8266:esp8266:generic
          platforms: |
              - name: esp8266:esp8266
                source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
          sketch-paths: 'ESP_PixelFan'
          verbose: true
